  # ------------------------------------------------------------------------------
  auth:
    extends:
      file: ${DCAPE_ROOT}/docker-compose.dcape.yml
      service: template-traefik
    image: ${NARRA_IMAGE}:${NARRA_VER}
    command:
      --as.host ${NARRA_GITEA_URL} --as.cookie_sign ${NARRA_SIGN_KEY} --as.cookie_crypt ${NARRA_CRYPT_KEY}
      --as.client_id ${NARRA_CLIENT_ID} --as.client_key ${NARRA_CLIENT_KEY}
      --as.my_url=${DCAPE_SCHEME}://${DCAPE_HOST} --as.do401 --as.cookie_domain ${DCAPE_DOMAIN}
      --fs.path=/html --fs.protect=/private/
    labels:
      - "traefik.http.routers.narra.rule=Host(`${DCAPE_HOST}`)"
      - "traefik.http.services.narra.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.narra.forwardauth.address=${DCAPE_SCHEME}://${DCAPE_HOST}/auth"
      - "traefik.http.middlewares.narra.forwardauth.authResponseHeaders=X-Username"
    volumes:
      - ./apps/narra/html:/html:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
